name: Arduino Compile
on: [push]

jobs: 
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - name: "rp2040:rp2040"
              source-url: "https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json"
          fqbn: rp2040:rp2040
          sketch-paths: |
            - ./device
          libraries: |
            "Adafruit Fingerprint Sensor Library"

