name: Arduino Compile
on: [push, pull_request]

jobs:
  arduino-compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Download (Earle F. Philhower, III) RP2040 core
        run: arduino-cli core update-index --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

      - name: Install (Earle F. Philower, III) RP2040 core
        run: arduino-cli core install rp2040:rp2040@3.0.0 --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

      - name: Download Libraries
        run: arduino-cli lib download "Adafruit Fingerprint Sensor Library"
      
      - name: Install Libraries
        run: arduino-cli lib install "Adafruit Fingerprint Sensor Library"

      - name: Compile Sketch
        run: arduino-cli compile device/ --fqbn rp2040:rp2040:rpipicow --build-path ./build/device --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

      - name: Push build to build branch
        uses: EndBug/add-and-commit@v9
        with:
          add: ".build"
          branch: build
          push: true
          force: true