name: Arduino Compile
on: [push, pull_request]

jobs: 
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/actions/libraries/compile-sketches@v1
        with:
          fqbn: earlephilhower:rp2040:rp2040
          sketch-paths: |
            - ./picow
          libraries: |
            - name: Adafruit_Fingerprint_Sensor
              version: 1.0.0
