name: Arduino Compile
on: [push]

jobs: 
  compile-sketch:

    runs-on: ubuntu-latest
    steps:
      fail-fast: false
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: rp2040:rp2040
          sketch-paths: |
            - ./picow
          libraries: |
            - name: Adafruit_Fingerprint_Sensor

